version: '2'

services:

  mariadb:
    image: digidock.dev.tgp.digicert.com:5000/digisqldb
    ports:
      - 3306:3306
    volumes:
      - /c/Users/james.wang/eclipse-workspace/.digisql_data/data:/var/lib/mysql
    network_mode: bridge

  kafka:
    image: landoop/fast-data-dev
    environment:
      ADV_HOST: localhost.digicert.com
      RUNTESTS: 0                       # Disable Running tests so the cluster starts faster
    ports:
      - 2181:2181                       # Zookeeper
      - 3030:3030                       # Landoop UI
      - 8081-8083:8081-8083             # REST Proxy, Schema Registry, Kafka Connect ports
      - 9581-9585:9581-9585             # JMX Ports
      - 9092:9092                       # Kafka Broker
    network_mode: bridge

  dse:
    image: datastax/dse-server
    environment:
      - DS_LICENSE=accept
    ports:
      - 8983:8983                       # Solr REST
      - 9042:9042                       # Cassandra
    command: ["-s"]
    cap_add:
      - IPC_LOCK
    ulimits:
      memlock: -1
    network_mode: bridge
